# Generated by Django 4.1.7 on 2023-05-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_car_fuel_economy_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.car')),
                ('car_name', models.CharField(max_length=200)),
            ],
        ),
    ]
