# Generated by Django 4.1.7 on 2023-06-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
